[package]
name = "pharmsol"
version = "0.1.0"
edition = "2021"
authors = [
    "Julián D. Otálvaro <juliandavid347@gmail.com>",
    "Markus Hovd",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.83"
csv = "1.3.0"
dashmap = "5.5.3"
diffsol = "0.1.6"
lazy_static = "1.4.0"
nalgebra = "0.32.5"
ndarray = { version = "0.15.6", features = ["rayon"] }
rayon = "1.10.0"
serde = { version= "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
