// We need to forward-declare the Rust entrypoints to silence -Wmissing-prototypes
// and so that the dynamic linker can find them. extendr generates wrappers with
// a `wrap__` prefix for every exposed function.

#include <stdint.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>
#include <R_ext/Visibility.h>

/* Generated by extendr */
SEXP wrap__compile_model(SEXP text);
SEXP wrap__simulate_subject(SEXP model, SEXP params, SEXP times, SEXP evids,
                            SEXP amts, SEXP durs, SEXP cmts, SEXP outeqs,
                            SEXP cov_names, SEXP cov_times, SEXP cov_values);

static const R_CallMethodDef CallEntries[] = {
    {"wrap__compile_model",     (DL_FUNC) &wrap__compile_model,     1},
    {"wrap__simulate_subject",  (DL_FUNC) &wrap__simulate_subject, 11},
    {NULL, NULL, 0}
};

void attribute_visible R_init_pharmsolr(DllInfo *info) {
    R_registerRoutines(info, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(info, FALSE);
}
