name: Benchmark (PR)

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - "**"

jobs:
  benchmark_pr_branch:
    name: Continuous Benchmarking PRs with Bencher
    # Only run if the test workflow succeeded and it's from a PR
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.head_repository.full_name == github.repository
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: bencherdev/bencher@main
      - name: Get PR details
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pulls = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${context.payload.workflow_run.head_branch}`
            });
            if (pulls.data.length > 0) {
              const pr = pulls.data[0];
              core.setOutput('number', pr.number);
              core.setOutput('head_ref', pr.head.ref);
              core.setOutput('base_ref', pr.base.ref);
              core.setOutput('base_sha', pr.base.sha);
            }
      - name: Track PR Benchmarks with Bencher
        if: steps.pr.outputs.number != ''
        run: |
          bencher run \
          --project pharmsol \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch "${{ steps.pr.outputs.head_ref }}" \
          --start-point "${{ steps.pr.outputs.base_ref }}" \
          --start-point-hash '${{ steps.pr.outputs.base_sha }}' \
          --start-point-clone-thresholds \
          --start-point-reset \
          --testbed ${{ runner.name }} \
          --err \
          --adapter rust_criterion \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          cargo bench
